name: SendingnNetwork
attributes:
  ORGANIZATIONNAME: sdn.org

configs:
  Debug: debug
  Release: release

fileGroups:
    - README.md
    - CHANGES.md
    - AUTHORS.rst
    - Podfile
    - project.yml
    - changelog.d

configFiles:
  Debug: Config/Project-Debug.xcconfig
  Release: Config/Project-Release.xcconfig

options:
  defaultConfig: Release
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
  createIntermediateGroups: true
  useBaseInternationalization: true
  postGenCommand: sh Tools/XcodeGen/postGenCommand.sh
    
include:
  - path: SendingnNetwork/target.yml
  - path: SendingnNetworkTests/target.yml
  - path: SendingnNetworkNSE/target.yml
  - path: DesignKit/target.yml
  - path: SendingnNetworkSwiftUI/target.yml
  - path: SendingnNetworkSwiftUI/targetUnitTests.yml
  - path: SendingnNetworkSwiftUI/targetUITests.yml
  - path: CommonKit/target.yml
  - path: CommonKit/targetUnitTests.yml
  # Disabled due to crypto corruption issues.
  # https://github.com/Sending-Network/sendingnetwork-ios/issues/7618
  # - path: SendingnNetworkShareExtension/target.yml
  # - path: SiriIntents/target.yml

packages:
  AnalyticsEvents:
    url: https://github.com/matrix-org/matrix-analytics-events
    exactVersion: 0.5.0
  Mapbox:
    url: https://github.com/maplibre/maplibre-gl-native-distribution
    minVersion: 5.12.2
    maxVersion: 5.13.0
  OrderedCollections:
    url: https://github.com/apple/swift-collections
    minVersion: 1.0.2
    maxVersion: 2.0.0
  SwiftOGG:
    url: https://github.com/vector-im/swift-ogg
    branch: 0.0.1
  WysiwygComposer:
    url: https://github.com/matrix-org/matrix-wysiwyg-composer-swift
    version: 2.2.2
  DeviceKit:
    url: https://github.com/devicekit/DeviceKit
    majorVersion: 4.7.0
  DTCoreText:
    url: https://github.com/Cocoanetics/DTCoreText
    version: 1.6.27
